version: '3.1'
services:
  voting_systems_db:
    container_name: voting_systems_db
    image: postgres:15.8-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"